# Set up the environment with the required packages.

library(assertthat)
library(data.table)
library(dplyr)
library(ggplot2)
# This should be V3.2.0
remotes::install_github("jgcri/hector@a61d64a")
library(hector)
#stopifnot(packageVersion("hector") == "3.2.0")




library(magrittr)
library(zoo)
#remotes::install_github("jgcri/rgcam")
library(rgcam)

# The date when Hector will start getting emissions from GCAM
TRANSITION_DATE <- 2005

# All of the emissions that eventually will be generated by GCAM and passed to Hector
GCAM_EMISS <- c("ffi_emissions", "luc_emissions", "daccs_uptake", "luc_uptake", "BC_emissions", "C2F6_emissions",
                "CF4_emissions", "CH4_emissions", "CO_emissions", "HFC125_emissions", "HFC134a_emissions",  "HFC143a_emissions",
                "HFC227ea_emissions", "HFC23_emissions", "HFC245fa_emissions", "HFC32_emissions", "N2O_emissions", "NH3_emissions" ,
                "NMVOC_emissions", "NOX_emissions", "OC_emissions", "SF6_emissions", "SO2_emissions")
DEFAULT_EMISS <- c("CCl4_emissions", "CFC113_emissions", "CFC114_emissions", "CFC115_emissions", "CFC11_emissions",
                   "CFC12_emissions", "CH3Br_emissions", "CH3CCl3_emissions", "CH3Cl_emissions", "HCFC141b_emissions",
                   "HCFC142b_emissions", "HCFC22_emissions", "HFC4310_emissions", "RF_albedo", "SV" ,
                   "halon1211_emissions", "halon2402_emissions", "halon1301_emissions")


GCAM_EMISS_FILE <- "auxiliary_data/gcam_emissions.csv"
DEFAULT_EMISS_FILE <- "auxiliary_data/default_emissions.csv"
QUERY_FILE <- "auxiliary_data/hector-queries.xml"

EMISS_MAP <- read.csv("auxiliary_data/GCAM_hector_emissions_map.csv")

